# Dockerfile для dev-сервера фронтенда
FROM node:18.20.4-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходники (будут перезаписаны volume)
COPY . .

EXPOSE 5173

# Запускаем dev-сервер Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]




